name: zip builder

on:
  push:
    branches:
      - master
      - main
  repository_dispatch:
    types: [make_zip]
  workflow_dispatch:
    inputs:
      tag:
        default: "latest"
        description: "Release tag"
        required: true

jobs:
  make-zip:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: "rabbit_queue_checker.zip"
      DEFAULT_TAG: "latest"
      LAMBDA_BUILDER: "lambci/lambda:build-python3.8"
    steps:
    - name: Echo tag
      run: |
        echo "input"
        echo ${{ github.event.inputs.tag }}
        echo "env"
        echo ${{ env.DEFAULT_TAG }}
        echo "result"
        USER_INPUT=${{ github.event.inputs.tag }}
        DEFAULT_VALUE=${{ env.DEFAULT_TAG }}
        echo ${USER_INPUT:=DEFAULT_VALUE}
        echo ${"${{ github.event.inputs.tag }}":="${{ env.DEFAULT_TAG }}"}
    - uses: actions/checkout@v3
    - name: setting up docker builder
      run: docker run --rm -v $(pwd):/var/task $LAMBDA_BUILDER pip install -r requirements.txt -t /var/task/ --no-cache-dir --compile
    - name: zipping
      run: zip -r -9 $ARTIFACT_NAME .
#    - name: Create artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: task_zip
#        path: ./${{env.ARTIFACT_NAME}}
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: ./${{ env.ARTIFACT_NAME }}
        makeLatest: true
        allowUpdates: true
        tag: ${github.event.inputs.tag:=env.DEFAULT_TAG}
