name: zip builder

on:
  push:
    branches:
      - master
      - main
  repository_dispatch:
    types: [make_zip]
  workflow_dispatch:

jobs:
  make-zip:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: rabbit_queue_checker.zip
      LAMBDA_BUILDER: "lambci/lambda:build-python3.8"
    steps:
    - uses: actions/checkout@v3
    - name: setting up docker builder
      run: docker run --rm -v .:/var/task $LAMBDA_BUILDER pip install -r requirements.txt -t /var/task/ --no-cache-dir --compile
    - name: zipping
      run: zip -r -9 $ARTIFACT_NAME .
    - uses: actions/upload-artifact@v3
      with:
        name: rabbit_queue_checker
        path: $ARTIFACT_NAME